name: drone_env
channels:
  - defaults
dependencies:
  - python=3.11
  - geopandas
  - pandas
  - networkx
  - osmnx
  - shapely
  - geopy
  - matplotlib
  - pip
  - pip:
    - subprocess
    - pickle-mixin
